openapi: 3.0.0
info:
  title: Example API
  description: An example API for a lambda function
  version: 1.0.0
servers:
  - url: http://localhost:9999
paths:
  /:
    get:
      summary: Hello world
      description: Returns a json message
      responses:
        200:
          description: Success
          headers:
            X-Request-ID: 
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                    example: "lambda"
